### ISSUE TITLE
Graphical problem with insert credits  from version 2.1 and up

### ISSUE THREAD

**Issue by 1amgoingin** [argonlefou/Hotd3pc_ArcadeMod#1]
Here is the image of the game started with arcade  mod 2.0
![THE HOUSE OF THE DEAD 3 1_25_2023 4_04_36 PM](https://user-images.githubusercontent.com/22461272/214599092-7c4c9d44-ec8a-4ba5-ad18-1737da97ba04.png)

and here it is with 5.1
![THE HOUSE OF THE DEAD 3 1_25_2023 4_03_45 PM](https://user-images.githubusercontent.com/22461272/214599157-647e9029-cc3d-439e-bbfa-320e38cf4fc9.png)

**Comment by argonlefou** [comment]
Try to remove all old files from previous patch and extract newer versions.
Especially the MemoryData folder, older - now non necessary - files (that have been removed on newer builds) can conflict with the new unpacked launcher

Also, there is no 2.1 version
It should be better to specify exactly which one is not working

**Comment by VooDooUdo2** [comment]
I think I know what happened.  I was having the exact same issue as 1amgoingin.  I was able to resolve it by applying a no-cd fix to the hod3pc.exe file.  Before I was just keeping an image of the CD mounted.  I am guessing that argonlefou developed the mod using the patched exe, and if you try to use it with the unpatched on you get the above issue.

Edit: And I'd have known there are only certain supported exe's if I had actually read the Readme - shame on me.  At any rate the EXE that was giving me the above screen has an MD5 of e4819dcf2105b85a7e7bc9dc66159f5c which the Readme says should work, but it didn't seem to.  Once I applied the no-cd patch it now has MD5 of b8af47f16d5e43cddad8df0a6fdb46f5 which seems to work fine.  This was all done using the latest release of the mod (5.1.0).

**Comment by argonlefou** [comment]
> I think I know what happened. I was having the exact same issue as 1amgoingin. I was able to resolve it by applying a no-cd fix to the hod3pc.exe file. Before I was just keeping an image of the CD mounted. I am guessing that argonlefou developed the mod using the patched exe, and if you try to use it with the unpatched on you get the above issue.
> 
> Edit: And I'd have known there are only certain supported exe's if I had actually read the Readme - shame on me. At any rate the EXE that was giving me the above screen has an MD5 of e4819dcf2105b85a7e7bc9dc66159f5c which the Readme says should work, but it didn't seem to. Once I applied the no-cd patch it now has MD5 of b8af47f16d5e43cddad8df0a6fdb46f5 which seems to work fine. This was all done using the latest release of the mod (5.1.0).

Thanks for this very usefull information !
Indeed, this version "e4819dcf2105b85a7e7bc9dc66159f5c" is - so far - the only one binary having different memory location. That's why I need a separate file to load data (you'll find it under \MemoryData\e4819dcf2105b85a7e7bc9dc66159f5c.cfg)

Unfortunatelly, It looks like I forgot to change some values in it, while I working on the plugin with hardcoded values (used for every other binaries) in the Launcher

I can't test this binary (I don't have this version of the game with the CD, only the binary file to Hex-Analyse it) but if you can try to replace the faulty file with the content of this archive :  
[e4819dcf2105b85a7e7bc9dc66159f5c.zip](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/10509961/e4819dcf2105b85a7e7bc9dc66159f5c.zip)

And report back, I'd be able to update the release and correct that bug

**Comment by VooDooUdo2** [comment]
I will do so, got busy with work today, but tomorrow I should have some time to test it out.  Thanks for all the great work you do!

**Comment by 1amgoingin** [comment]
Well with the new cfg file it shows the first screen ok, and I can add the credits, but as soon as I hit start for player one it just crashes.

**Comment by argonlefou** [comment]
Ok...thanks !
I will have to check again the full file this week end , but this will take a bit a time

In the meantime, using a different exe (like a no-cd) should make you able to play untill I fix it

**Comment by 1amgoingin** [comment]
Yeah I managed to play with different exe as VooDooUdo2 pointed out, I didn't notice any problems, so there is that.

**Comment by argonlefou** [comment]
This file should correct any issue with that particular version.
It would be nice to confirm on your side, so that I can update it for everybody

[e4819dcf2105b85a7e7bc9dc66159f5c.zip](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/10569542/e4819dcf2105b85a7e7bc9dc66159f5c.zip)

**Comment by 1amgoingin** [comment]
Ok, now it runs, The insert credits first scene is ok, but when I start to actually play I can manage to shoot 6 rounds, than when the game says reload when I press the trigger the game closes itself. It is not time based I tested it, there is something about the no bullets and reload.

**Comment by argonlefou** [comment]
Could you run the launcher  by powershell/command line and add a "-v" option at the end of the command ? (like `Hotd3Arcade_Launcher.exe -v`) 

This should create a debug file on the folder, to share it here if possible

**Comment by argonlefou** [comment]
This particular binary (MD5 hash = e4819dcf2105b85a7e7bc9dc66159f5c)  has been corrected in v6.0 and is now working like all the other ones
