### ISSUE TITLE
Hotd3Arcade_Config.exe not found

### ISSUE THREAD

**Issue by BlackJeanBar** [argonlefou/Hotd3pc_ArcadeMod#10]
Hello, I didn't find the file Hotd3Arcade_Config.exe in any folder after unzipped it.

**Comment by argonlefou** [comment]
What zip files are you downloading ? Source code or release file ?

Make sure to get the [release](https://github.com/argonlefou/Hotd3pc_ArcadeMod/releases/tag/v7.0) , the file you're looking for is in it

Also make sure your antivirus is not removing the file afeter extraction

**Comment by BlackJeanBar** [comment]
Oh my bad, I just get the source code sorry.
Thank's a lot.
Best regards
