### ISSUE TITLE
Hotd3Arcade_Config can increase the auto-reload option?

### ISSUE THREAD

**Issue by fsxiyu** [argonlefou/Hotd3pc_ArcadeMod#11]
Such as title, thank you!

**Comment by argonlefou** [comment]
I'm sorry but I don't understand what you mean by "increase the auto-reload option"

**Comment by fsxiyu** [comment]
> I'm sorry but I don't understand what you mean by "increase the auto-reload option"

I wish I could choose whether or not to Auto-Reload bullets in the game.

**Comment by argonlefou** [comment]
Auto-reload is not part of the original arcade game, and the purpose of that mod is to mimic it as close as possible.

#3 already have some discussion about it, and you'll find a compiled version to download with the auto-reload feature at the very bottom of the thread
