### ISSUE TITLE
Insert CD-ROM?

### ISSUE THREAD

**Issue by PSPNDSGBASP** [argonlefou/Hotd3pc_ArcadeMod#2]
Great job!
Version 1 working fine on my computer.
However after running version 2 or later, it asks me to insert CD-ROM and stop working.
Is it normal?
Thanks!

**Comment by argonlefou** [comment]
The mod never had any "NO-CD" patch included on it, so you need to set your game correctly before using the mod.

You can optionally run the last updated 5.1 launcher by command line, and adding a _**-v**_ option to get a debug file that you can share here.
