### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by MarceloF1000** [argonlefou/Hotd3pc_ArcadeMod#5]
I followed the instructions to configure it but when I run Hotd3Arcade_Launcher.exe I can see the process in Task Manager along with hod3pc.exe for a couple of seconds and then both close. Running as administrator did not make a difference.

Can you have a look at the debug file?
[Debug_2023-04-28_18-45-34.txt](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/11351740/Debug_2023-04-28_18-45-34.txt)

**Comment by argonlefou** [comment]
Your log stops in the init phase, one of the mods is making the exe to crash.

I can't check for now, I'll try later.

You can try with another release/binary untill then

**Comment by MarceloF1000** [comment]
I tried with the RELOADED cracked version and the game works, but player 1 gun cannot reload and when player 2 gun joins the game and pulls the trigger both guns fire and outputs such as recoil and damage also occur on both guns.

I'm using 2 GUN4IR guns set up as P1 and P2 in DemulShooter 10.9.7.0. If I run the game windowed with mamehooker debug window side by side, I can see recoil changing values for both P1 and P2 when only P2 pulls the trigger. This behaviour does not happen with other games such as HOTD 4.

**Comment by argonlefou** [comment]
> I tried with the RELOADED cracked version and the game works, 

So this may confirm a issue with the memory location used for your initial binary.
I may have to ask you a copy of you exe in the future to check again, as I don't think I kept a copy of all different versions I've ran into.
There are a lot of them and so far they were all using the same binary location, except for one.

>but player 1 gun cannot reload and when player 2 gun joins the game and pulls the trigger both guns fire and outputs such as recoil and damage also occur on both guns.
> 
> I'm using 2 GUN4IR guns set up as P1 and P2 in DemulShooter 10.9.7.0. If I run the game windowed with mamehooker debug window side by side, I can see recoil changing values for both P1 and P2 when only P2 pulls the trigger. This behaviour does not happen with other games such as HOTD 4.

For Inputs, I can only suggest to check that both player have been set to KEYBOARD on the arcade mod config tool
But unless some faulty configuration somewhere (or something that went very wrong somewhere) the fact that P1/P2 got mixed for Input AND outputs (outputs like damage have no relation whatsoever with the input hardware) is purely impossible (and working behavior confirmed by alot of people, especially with that RELOADED version)

**Comment by MarceloF1000** [comment]
I made a silly mistake. I selected keyboard for both guns in the game launcher, but forgot to do the same in the Arcade Mod. I had P1 set to mouse and this is what was causing the crazy behaviour. The guns all work fine now. Sorry for wasting your time.

As for the RELOADED version I'm using, you can find it here:
https://archive.org/details/the-house-of-the-dead-3-reloaded

**Comment by argonlefou** [comment]
Thanks, but the file I'll need would be the original one you tested (the one that did not start) instead of the RELOAD version

As a sidenote, while using the ArcadeMod, almost all options from the original loader are overwriten by the mod so the only settings that matter are the ones from the ArcadeLauncher tool

**Comment by MarceloF1000** [comment]
[The-House-of-the-Dead-III_NoCD_Win_EN.zip](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/11361525/The-House-of-the-Dead-III_NoCD_Win_EN.zip)
[hod3pc.zip](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/11361535/hod3pc.zip)

I'm not 100% sure, but I think I was using one of these 2 files. Hard to tell because I installed the game more than a year ago and since I've reinstalled the game the previous files were removed or overwritten.

**Comment by argonlefou** [comment]
Second link had a Virus warning from Windows defender so I didn't test it.

First link has the same MD5 chacksum than the one listed on your initial debug file, so it should have been this one.
I tested it on my computer and it's working as expected.

So, with that successfull test and the fact that you managed to run the RELOADED version before that, I'm closing that ticket
