### ISSUE TITLE
Showing score (unable to get the cheatcode on)

### ISSUE THREAD

**Issue by RadiantAnsel-MSD** [argonlefou/Hotd3pc_ArcadeMod#6]
Is there a possibility to add the score display to be always on, or have a variable to make it be on/off? To make it appear, in the original PC release, you had to do a code in the main menu, which of course you can't access with this release, so is there a way to make it be always on? Sort of like the PS3 version

**Comment by argonlefou** [comment]
Thanks for the information.

I've pushed an updated 6.0 version with this option added in the config tool
